#!/usr/bin/env python3
"""
Comprehensive tool reclassification and description fix script.
This script corrects categories and descriptions for items incorrectly labeled as "Tool".
"""

import json
import re

# Load data
with open('data.json', encoding='utf-8') as f:
    data = json.load(f)

# Generic/bad descriptions that need to be fixed
BAD_DESCRIPTIONS = {
    "Low-level systems programming language",
    "Statistical computing and graphics language",
    "Systems programming language",
    "Capability-based language",
    "Array programming for finance",
    "Simple, fast compiled language",
    "Array programming language",
    "Fast, statically typed language by Google",
    "Formal specification language",
    "Array language for kdb+",
}

# Known tools with their correct category and description
# Format: "name": ("category", "description")
KNOWN_TOOLS = {
    # Domain Registrars / Hosting
    "GoDaddy": ("Hosting", "Domain registrar, web hosting, and website builder platform"),
    "Hover": ("Hosting", "Domain name registrar focused on simplicity"),
    "Tucows": ("Hosting", "Internet services company and domain registrar"),
    "Namecheap": ("Hosting", "Domain registrar and web hosting provider"),
    "Name.com": ("Hosting", "Domain name registrar"),
    "Netlify": ("Hosting", "Static site hosting and serverless backend services"),
    "Vercel": ("Hosting", "Frontend cloud platform for static and serverless deployment"),
    "DigitalOcean": ("Cloud", "Cloud infrastructure provider"),
    "Linode": ("Cloud", "Cloud hosting and Linux virtual machines"),
    "cPanel": ("Hosting", "Web hosting control panel"),
    "DirectAdmin": ("Hosting", "Web hosting control panel"),
    "Plesk": ("Hosting", "Web hosting control panel"),
    "AlternC": ("Hosting", "Web hosting control panel"),
    "NearlyFreeSpeech": ("Hosting", "Web hosting provider"),
    "Hetzner": ("Cloud", "Cloud and dedicated server hosting"),
    "OVH": ("Cloud", "Cloud computing and web hosting provider"),
    "Cloudflare": ("CDN", "CDN, DDoS protection, and DNS services"),
    
    # Registry operators
    "auDA": ("Hosting", "Australian domain name registry"),
    "CentralNic": ("Hosting", "Domain name registry services"),
    "CIRA": ("Hosting", "Canadian Internet Registration Authority"),
    "CNNIC": ("Hosting", "China Internet Network Information Center"),
    "CZ.NIC": ("Hosting", "Czech domain registry"),
    "DENIC": ("Hosting", "German domain registry"),
    "NIC México": ("Hosting", "Mexican domain registry"),
    
    # IDEs and Editors
    "Visual Studio Code": ("IDE/Editor", "Lightweight code editor by Microsoft"),
    "Microsoft Visual Studio": ("IDE/Editor", "Full-featured IDE for Windows development"),
    "Xcode (Apple)": ("IDE/Editor", "IDE for macOS and iOS development"),
    "Eclipse": ("IDE/Editor", "Open-source Java IDE"),
    "IntelliJ IDEA": ("IDE/Editor", "Java IDE by JetBrains"),
    "PyCharm": ("IDE/Editor", "Python IDE by JetBrains"),
    "WebStorm": ("IDE/Editor", "JavaScript IDE by JetBrains"),
    "Atom": ("IDE/Editor", "Hackable text editor by GitHub"),
    "Sublime Text": ("IDE/Editor", "Fast cross-platform text editor"),
    "Notepad++": ("IDE/Editor", "Free source code editor for Windows"),
    "Notepad": ("IDE/Editor", "Basic text editor for Windows"),
    "Vim": ("IDE/Editor", "Highly configurable terminal text editor"),
    "Neovim": ("IDE/Editor", "Modern fork of Vim"),
    "Emacs": ("IDE/Editor", "Extensible text editor"),
    "XEmacs": ("IDE/Editor", "Fork of GNU Emacs"),
    "MicroEMACS": ("IDE/Editor", "Lightweight Emacs-style editor"),
    "nano": ("IDE/Editor", "Simple terminal text editor"),
    "Gedit": ("IDE/Editor", "Default text editor for GNOME"),
    "Kate": ("IDE/Editor", "Advanced text editor for KDE"),
    "Brackets": ("IDE/Editor", "Open-source editor for web design"),
    "Bluefish": ("IDE/Editor", "Advanced text editor for web development"),
    "Geany": ("IDE/Editor", "Lightweight IDE and text editor"),
    "Mousepad": ("IDE/Editor", "Simple text editor for Xfce"),
    "Xed": ("IDE/Editor", "Text editor for Linux Mint"),
    "CodeLite": ("IDE/Editor", "Open-source cross-platform IDE"),
    "Codelobster": ("IDE/Editor", "Free PHP IDE"),
    "CodeWarrior": ("IDE/Editor", "IDE by Metrowerks/NXP"),
    "MonoDevelop": ("IDE/Editor", "Cross-platform IDE for .NET"),
    "NetBeans": ("IDE/Editor", "Open-source IDE for Java"),
    "NetBeans C/C++ pack": ("IDE/Editor", "C/C++ development plugin for NetBeans"),
    "AppCode": ("IDE/Editor", "IDE for iOS/macOS development by JetBrains"),
    "CLion": ("IDE/Editor", "C/C++ IDE by JetBrains"),
    "GoLand": ("IDE/Editor", "Go IDE by JetBrains"),
    "Rider": ("IDE/Editor", ".NET IDE by JetBrains"),
    "PhpStorm": ("IDE/Editor", "PHP IDE by JetBrains"),
    "RubyMine": ("IDE/Editor", "Ruby IDE by JetBrains"),
    "DataGrip": ("IDE/Editor", "Database IDE by JetBrains"),
    "Fleet": ("IDE/Editor", "Lightweight IDE by JetBrains"),
    "Android Studio": ("IDE/Editor", "Official IDE for Android development"),
    "Dev-C++": ("IDE/Editor", "Free IDE for C/C++ programming"),
    "Dev-Pascal": ("IDE/Editor", "Free Pascal IDE"),
    "Lazarus": ("IDE/Editor", "Free cross-platform visual IDE for Object Pascal"),
    "Delphi": ("IDE/Editor", "IDE for Object Pascal development"),
    "Turbo Delphi": ("IDE/Editor", "Stripped-down version of Delphi"),
    "Zend Studio": ("IDE/Editor", "PHP IDE by Zend"),
    "Komodo IDE": ("IDE/Editor", "Cross-platform IDE for dynamic languages"),
    "Komodo Edit": ("IDE/Editor", "Free multi-language editor"),
    "ActiveState": ("IDE/Editor", "Developer tools and language distributions"),
    "Codeanywhere": ("IDE/Editor", "Cloud-based code editor"),
    "Cloud9 IDE": ("IDE/Editor", "Cloud-based development environment"),
    "Cloud IDE": ("IDE/Editor", "Browser-based development environment"),
    "Coda": ("IDE/Editor", "macOS web development editor"),
    "BBEdit": ("IDE/Editor", "Professional HTML and text editor for Mac"),
    "Bare Bones Software": ("IDE/Editor", "Developer of BBEdit and TextWrangler"),
    "TextMate": ("IDE/Editor", "Powerful macOS text editor"),
    "UltraEdit": ("IDE/Editor", "Commercial text and code editor"),
    "EditPlus": ("IDE/Editor", "Text editor for Windows"),
    "SlickEdit": ("IDE/Editor", "Multi-language code editor"),
    "Zeus IDE": ("IDE/Editor", "Windows IDE for programmers"),
    "Brief": ("IDE/Editor", "Programmer's text editor"),
    "MultiEdit": ("IDE/Editor", "Windows programmer's editor"),
    "MEd": ("IDE/Editor", "Text editor"),
    "GoldED": ("IDE/Editor", "Text editor for Amiga"),
    "CygnusEd": ("IDE/Editor", "Text editor for Amiga"),
    "Colossal Typewriter": ("IDE/Editor", "Early text editor"),
    "Acme": ("IDE/Editor", "Text editor from Plan 9"),
    "nvi": ("IDE/Editor", "Berkeley vi editor"),
    "MinEd": ("IDE/Editor", "Minimalist text editor"),
    "BlueJ": ("IDE/Editor", "Java IDE for education"),
    "DrJava": ("IDE/Editor", "Lightweight Java IDE"),
    "JCreator": ("IDE/Editor", "Java IDE for Windows"),
    "jEdit": ("IDE/Editor", "Programmer's text editor in Java"),
    "MyEclipse": ("IDE/Editor", "Commercial Eclipse-based IDE"),
    "RStudio": ("IDE/Editor", "IDE for R programming"),
    "Spyder": ("IDE/Editor", "Scientific Python IDE"),
    "IDLE": ("IDE/Editor", "Python's default IDE"),
    "Thonny": ("IDE/Editor", "Python IDE for beginners"),
    "Eric": ("IDE/Editor", "Full-featured Python IDE"),
    "Wing IDE": ("IDE/Editor", "Python IDE by Wingware"),
    "LiteIDE": ("IDE/Editor", "Simple Go IDE"),
    "Qt Creator": ("IDE/Editor", "Cross-platform IDE for Qt development"),
    "KDevelop": ("IDE/Editor", "Cross-platform IDE for C/C++ and more"),
    "Anjuta": ("IDE/Editor", "GNOME IDE for C/C++"),
    "Code::Blocks": ("IDE/Editor", "Open-source C/C++ IDE"),
    "Orwell Dev-C++": ("IDE/Editor", "Fork of Dev-C++"),
    "Pelles C": ("IDE/Editor", "C development environment for Windows"),
    "Open Watcom": ("IDE/Editor", "Open-source C/C++ compiler and IDE"),
    "Watcom": ("IDE/Editor", "C/C++ compiler and IDE"),
    "LabVIEW": ("IDE/Editor", "Visual programming environment for engineers"),
    "MATLAB": ("IDE/Editor", "Numerical computing environment"),
    "Octave": ("IDE/Editor", "Free MATLAB alternative"),
    "Scilab": ("IDE/Editor", "Open-source numerical computing"),
    "DevEco Studio": ("IDE/Editor", "HarmonyOS development IDE"),
    "HarmonyOS": ("Operating System", "Distributed operating system by Huawei"),
    "Decoda": ("IDE/Editor", "Lua debugging IDE"),
    "ZeroBrane Studio": ("IDE/Editor", "Lightweight Lua IDE"),
    "Yudit": ("IDE/Editor", "Unicode text editor"),
    "Metapad": ("IDE/Editor", "Lightweight Notepad replacement"),
    
    # Version Control
    "Git": ("Version Control", "Distributed version control system"),
    "GitHub": ("Version Control", "Git repository hosting service"),
    "GitLab": ("Version Control", "Git repository and DevOps platform"),
    "Bitbucket": ("Version Control", "Git and Mercurial repository hosting"),
    "Mercurial": ("Version Control", "Distributed version control system"),
    "Subversion": ("Version Control", "Centralized version control system"),
    "SVN": ("Version Control", "Centralized version control system"),
    "CVS": ("Version Control", "Concurrent Versions System"),
    "Perforce": ("Version Control", "Enterprise version control"),
    "Bazaar": ("Version Control", "Distributed version control system"),
    "Fossil": ("Version Control", "Distributed version control with wiki and bug tracking"),
    "Darcs": ("Version Control", "Distributed version control system"),
    "Monotone": ("Version Control", "Distributed version control system"),
    "Assembla": ("Version Control", "Git/SVN hosting and project management"),
    "Phabricator": ("Version Control", "Software development platform"),
    "Gitea": ("Version Control", "Self-hosted Git service"),
    "Gogs": ("Version Control", "Self-hosted Git service"),
    "SourceForge": ("Version Control", "Open-source project hosting"),
    "Launchpad": ("Version Control", "Collaboration platform by Canonical"),
    "GNU Savannah": ("Version Control", "Hosting for free software projects"),
    "Apache Allura": ("Version Control", "Open-source project hosting platform"),
    "Apache Bloodhound": ("Version Control", "Project management and bug tracking"),
    
    # CMS
    "WordPress": ("CMS", "Popular open-source content management system"),
    "Drupal": ("CMS", "Enterprise content management system"),
    "Joomla": ("CMS", "Open-source content management system"),
    "TYPO3": ("CMS", "Enterprise content management system"),
    "MediaWiki": ("CMS", "Wiki software used by Wikipedia"),
    "DokuWiki": ("CMS", "Simple wiki software"),
    "XWiki": ("CMS", "Enterprise wiki platform"),
    "Confluence": ("CMS", "Team collaboration and wiki software"),
    "Ghost": ("CMS", "Modern publishing platform"),
    "Hugo": ("CMS", "Fast static site generator"),
    "Jekyll": ("CMS", "Simple static site generator"),
    "Gatsby": ("CMS", "React-based static site generator"),
    "Hexo": ("CMS", "Fast blog framework"),
    "Pelican": ("CMS", "Static site generator written in Python"),
    "Grav": ("CMS", "Flat-file CMS"),
    "Kirby": ("CMS", "File-based CMS"),
    "Statamic": ("CMS", "Flat-file Laravel CMS"),
    "Craft CMS": ("CMS", "Flexible content management system"),
    "ExpressionEngine": ("CMS", "Flexible content management system"),
    "Contao": ("CMS", "Open-source content management system"),
    "ProcessWire": ("CMS", "Content management system and CMF"),
    "SilverStripe": ("CMS", "Open-source CMS and framework"),
    "Concrete CMS": ("CMS", "User-friendly content management system"),
    "Textpattern": ("CMS", "Elegant content management system"),
    "Serendipity": ("CMS", "PHP blog and CMS"),
    "b2evolution": ("CMS", "Multi-blog content management system"),
    "Movable Type": ("CMS", "Blog publishing platform"),
    "Blog software": ("CMS", "Software for creating and managing blogs"),
    "Nucleus CMS": ("CMS", "PHP/MySQL blog CMS"),
    "Habari": ("CMS", "Modern blogging platform"),
    "Pivot": ("CMS", "Weblog platform"),
    "Plone": ("CMS", "Enterprise CMS built on Zope"),
    "Zope": ("CMS", "Python-based web application server"),
    "Midgard CMS": ("CMS", "Content management framework"),
    "eZ Platform": ("CMS", "Enterprise CMS"),
    "eZ Publish": ("CMS", "Enterprise content management"),
    "Magnolia": ("CMS", "Enterprise headless CMS"),
    "Hippo CMS": ("CMS", "Java-based enterprise CMS"),
    "Bloomreach Experience Manager": ("CMS", "Digital experience platform"),
    "Adobe Experience Manager": ("CMS", "Enterprise content management"),
    "Sitecore": ("CMS", "Enterprise CMS and digital experience platform"),
    "Kentico": ("CMS", "ASP.NET CMS and digital experience platform"),
    "Umbraco": ("CMS", ".NET open-source CMS"),
    "Sitefinity": ("CMS", ".NET CMS by Progress"),
    "Orchard CMS": ("CMS", "Open-source ASP.NET CMS"),
    "DNN (DotNetNuke)": ("CMS", ".NET web content management"),
    "mojoPortal": ("CMS", ".NET web content management"),
    "Kooboo": ("CMS", ".NET web development platform"),
    "Composite C1": ("CMS", ".NET CMS"),
    "C1 CMS": ("CMS", ".NET CMS (formerly Composite C1)"),
    "Tridion": ("CMS", "Enterprise web content management"),
    "CoreMedia Content Cloud": ("CMS", "Enterprise CMS"),
    "censhare": ("CMS", "Content management platform"),
    "Contentverse": ("CMS", "Document and content management"),
    "BLOX CMS": ("CMS", "CMS for news organizations"),
    "CMS Made Simple": ("CMS", "User-friendly open-source CMS"),
    "CMSimple": ("CMS", "Simple flat-file CMS"),
    "GetSimple": ("CMS", "XML-based flat-file CMS"),
    "Pico": ("CMS", "Flat-file CMS"),
    "Bolt (CMS)": ("CMS", "Sophisticated lightweight CMS"),
    "OctoberCMS": ("CMS", "Laravel-based CMS"),
    "PyroCMS": ("CMS", "Laravel-powered CMS"),
    "Pagekit": ("CMS", "Modern open-source CMS"),
    "Anchor CMS": ("CMS", "Lightweight blogging CMS"),
    "Backdrop CMS": ("CMS", "Drupal fork for small teams"),
    "Bricolage": ("CMS", "Enterprise-class content management"),
    "Squiz Matrix": ("CMS", "Enterprise CMS"),
    "Cloud CMS": ("CMS", "API-first content management"),
    "Contentful": ("CMS", "Headless content management"),
    "Strapi": ("CMS", "Open-source headless CMS"),
    "Sanity": ("CMS", "Structured content platform"),
    "Prismic": ("CMS", "Headless website builder"),
    "Storyblok": ("CMS", "Visual headless CMS"),
    "Directus": ("CMS", "Open-source headless CMS"),
    "KeystoneJS": ("CMS", "Node.js headless CMS"),
    "Apostrophe": ("CMS", "Node.js CMS"),
    "OpenCms": ("CMS", "Java-based enterprise CMS"),
    "Hippo": ("CMS", "Java open-source CMS"),
    "dotCMS": ("CMS", "Cloud-native headless CMS"),
    "Alfresco": ("CMS", "Enterprise content management"),
    "Nuxeo": ("CMS", "Content services platform"),
    "Liferay": ("CMS", "Enterprise portal and CMS"),
    "Component content management system (CCMS)": ("CMS", "For structured content reuse"),
    "content management frameworks": ("CMS", "Frameworks for building CMS"),
    "Zesty.io": ("CMS", "SaaS headless CMS"),
    "WebGUI": ("CMS", "Perl-based CMS"),
    "Radiant CMS": ("CMS", "Ruby-based CMS"),
    "Refinery CMS": ("CMS", "Rails CMS"),
    "Locomotive CMS": ("CMS", "Ruby CMS with Liquid templates"),
    "Camaleon CMS": ("CMS", "Rails CMS"),
    "LocomotiveCMS": ("CMS", "Ruby-based content management"),
    "django CMS": ("CMS", "Python CMS built on Django"),
    "Wagtail": ("CMS", "Django content management system"),
    "Mezzanine": ("CMS", "Django CMS"),
    "Plumi": ("CMS", "Video sharing CMS"),
    "ATutor": ("CMS", "Learning content management system"),
    "Moodle": ("CMS", "Learning management system"),
    
    # Collaboration & Project Management
    "Basecamp": ("Collaboration", "Project management and team collaboration"),
    "Asana": ("Collaboration", "Work management platform"),
    "Trello": ("Collaboration", "Kanban-style project management"),
    "Monday.com": ("Collaboration", "Work operating system"),
    "Jira": ("Collaboration", "Issue and project tracking"),
    "Notion": ("Collaboration", "All-in-one workspace"),
    "Slack": ("Collaboration", "Team messaging and collaboration"),
    "Microsoft Teams": ("Collaboration", "Team collaboration platform"),
    "Discord": ("Collaboration", "Voice, video, and text communication"),
    "Zoom": ("Collaboration", "Video conferencing platform"),
    "Confluence": ("Collaboration", "Team workspace and wiki"),
    "Microsoft SharePoint Server": ("Collaboration", "Enterprise collaboration platform"),
    "SharePoint": ("Collaboration", "Enterprise collaboration platform"),
    "Copper Project": ("Collaboration", "CRM and project management"),
    "Clarizen": ("Collaboration", "Enterprise project management"),
    "Wrike": ("Collaboration", "Work management platform"),
    "Smartsheet": ("Collaboration", "Work execution platform"),
    "Teamwork": ("Collaboration", "Project management software"),
    "ClickUp": ("Collaboration", "Productivity platform"),
    "Airtable": ("Collaboration", "Spreadsheet-database hybrid"),
    "Coda": ("Collaboration", "All-in-one document platform"),
    "Quip": ("Collaboration", "Collaborative documents"),
    "Dropbox Paper": ("Collaboration", "Collaborative document workspace"),
    "Google Workspace": ("Collaboration", "Cloud productivity and collaboration"),
    "Microsoft 365": ("Collaboration", "Cloud productivity suite"),
    "Zoho Projects": ("Collaboration", "Project management software"),
    "Microsoft Project": ("Collaboration", "Project management software"),
    "Microsoft Office Project Server": ("Collaboration", "Enterprise project management"),
    "Planview": ("Collaboration", "Portfolio and work management"),
    "Primavera": ("Collaboration", "Enterprise project portfolio management"),
    "OmniPlan": ("Collaboration", "Project management for Mac"),
    "ConceptDraw Project": ("Collaboration", "Project management software"),
    "Calligra Plan": ("Collaboration", "Project management application"),
    "ProjectLibre": ("Collaboration", "Open-source project management"),
    "GanttProject": ("Collaboration", "Free project management"),
    "OpenProject": ("Collaboration", "Open-source project management"),
    "Redmine": ("Collaboration", "Project management web application"),
    "Trac": ("Collaboration", "Wiki and issue tracking"),
    "Taiga": ("Collaboration", "Agile project management"),
    "GitScrum": ("Collaboration", "Project management for teams"),
    "Leankit": ("Collaboration", "Lean project delivery"),
    "BigPicture": ("Collaboration", "Portfolio and project management for Jira"),
    "CEITON": ("Collaboration", "Workforce management"),
    "Tuleap": ("Collaboration", "Open-source ALM and DevOps platform"),
    "Collaborative software": ("Collaboration", "Software enabling team collaboration"),
    "Collabora Online": ("Collaboration", "Online office suite"),
    
    # Analytics
    "Google Analytics": ("Analytics", "Web analytics service"),
    "Microsoft Power BI": ("Analytics", "Business analytics service"),
    "MicroStrategy": ("Analytics", "Enterprise analytics platform"),
    "Tableau": ("Analytics", "Data visualization and analytics"),
    "Looker": ("Analytics", "Business intelligence platform"),
    "Qlik": ("Analytics", "Data analytics platform"),
    "Sisense": ("Analytics", "Business intelligence software"),
    "Domo": ("Analytics", "Business intelligence platform"),
    "Metabase": ("Analytics", "Open-source business intelligence"),
    "Redash": ("Analytics", "Data visualization and dashboards"),
    "Apache Superset": ("Analytics", "Data exploration and visualization"),
    "Grafana": ("Monitoring", "Metrics visualization and monitoring"),
    "Kibana": ("Analytics", "Data visualization for Elasticsearch"),
    "Splunk": ("Analytics", "Data platform for security and observability"),
    "Click analytics": ("Analytics", "Analysis of user click behavior"),
    "Click tracking": ("Analytics", "Tracking user click patterns"),
    
    # Office Suites
    "Microsoft Office": ("Collaboration", "Office productivity suite"),
    "Microsoft Word": ("Collaboration", "Word processing software"),
    "Microsoft Excel": ("Collaboration", "Spreadsheet software"),
    "Microsoft PowerPoint": ("Collaboration", "Presentation software"),
    "LibreOffice": ("Collaboration", "Free open-source office suite"),
    "OpenOffice": ("Collaboration", "Open-source office suite"),
    "Apache OpenOffice": ("Collaboration", "Open-source office suite"),
    "Apache OpenOffice Calc": ("Collaboration", "Spreadsheet application"),
    "Apache OpenOffice Writer": ("Collaboration", "Word processor"),
    "Google Docs": ("Collaboration", "Online word processor"),
    "Google Sheets": ("Collaboration", "Online spreadsheet"),
    "Apple iWork": ("Collaboration", "Apple's productivity suite"),
    "Pages": ("Collaboration", "Apple word processor"),
    "Numbers": ("Collaboration", "Apple spreadsheet"),
    "Keynote": ("Collaboration", "Apple presentation software"),
    "Calligra Suite": ("Collaboration", "KDE office suite"),
    "WPS Office": ("Collaboration", "Office productivity suite"),
    "OnlyOffice": ("Collaboration", "Online office suite"),
    "NeoOffice": ("Collaboration", "macOS office suite"),
    "Ability Office": ("Collaboration", "Microsoft-compatible office suite"),
    "24SevenOffice": ("Collaboration", "Cloud-based business software"),
    "SoftMaker Office": ("Collaboration", "Office suite"),
    "FreeOffice": ("Collaboration", "Free office suite"),
    "Calc": ("Collaboration", "Spreadsheet application"),
    "Gnumeric": ("Collaboration", "Spreadsheet application"),
    
    # Operating Systems
    "Windows": ("Operating System", "Operating system by Microsoft"),
    "Microsoft Windows": ("Operating System", "Operating system by Microsoft"),
    "Linux": ("Operating System", "Open-source Unix-like OS"),
    "Ubuntu": ("Operating System", "Popular Linux distribution"),
    "Debian": ("Operating System", "Stable Linux distribution"),
    "Fedora": ("Operating System", "Cutting-edge Linux distribution"),
    "CentOS": ("Operating System", "Enterprise Linux distribution"),
    "Red Hat": ("Operating System", "Enterprise Linux"),
    "SUSE": ("Operating System", "Enterprise Linux distribution"),
    "Arch Linux": ("Operating System", "Rolling-release Linux"),
    "Manjaro": ("Operating System", "Arch-based Linux"),
    "macOS": ("Operating System", "Apple's desktop OS"),
    "iOS": ("Operating System", "Apple's mobile OS"),
    "Android": ("Operating System", "Google's mobile OS"),
    "FreeBSD": ("Operating System", "Unix-like operating system"),
    "BSD": ("Operating System", "Unix-like operating system family"),
    "Xfce": ("Operating System", "Lightweight desktop environment"),
    "GNOME": ("Operating System", "Desktop environment"),
    "KDE": ("Operating System", "Desktop environment"),
    "CP/M": ("Operating System", "Early microcomputer OS"),
    "Concurrent CP/M": ("Operating System", "Multi-user CP/M"),
    "Concurrent CP/M-86": ("Operating System", "Multi-user CP/M for x86"),
    "DOS": ("Operating System", "Disk operating system"),
    "MS-DOS": ("Operating System", "Microsoft DOS"),
    "DR-DOS": ("Operating System", "Digital Research DOS"),
    "Novell DOS 7": ("Operating System", "DOS-compatible OS"),
    "OS/2": ("Operating System", "IBM operating system"),
    "QNX": ("Operating System", "Real-time operating system"),
    "VxWorks": ("Operating System", "Real-time operating system"),
    "RTOS": ("Operating System", "Real-time operating system"),
    "Minix": ("Operating System", "Unix-like operating system for education"),
    "Plan 9": ("Operating System", "Distributed operating system"),
    "Inferno": ("Operating System", "Distributed operating system"),
    "illumos": ("Operating System", "OpenSolaris-derived OS"),
    "OpenSolaris": ("Operating System", "Open-source Solaris"),
    "Solaris": ("Operating System", "Unix operating system"),
    "AIX": ("Operating System", "IBM Unix operating system"),
    "HP-UX": ("Operating System", "HP Unix operating system"),
    "Canonical": ("Operating System", "Company behind Ubuntu"),
    "Chromium": ("Operating System", "Open-source browser project"),
    "Chrome OS": ("Operating System", "Google's lightweight OS"),
    
    # Gaming/Hardware
    "Nintendo DS": ("Hardware", "Handheld gaming console"),
    "Nintendo Wii": ("Hardware", "Home gaming console"),
    "PlayStation": ("Hardware", "Sony gaming console"),
    "Xbox": ("Hardware", "Microsoft gaming console"),
    "Atari ST": ("Hardware", "16/32-bit home computer"),
    "Commodore 64": ("Hardware", "8-bit home computer"),
    "Amiga": ("Hardware", "Personal computer line"),
    "Apple II": ("Hardware", "8-bit home computer"),
    "CDC 6000 series": ("Hardware", "Mainframe computer series"),
    
    # Frameworks / Libraries
    "React": ("Frontend", "JavaScript library for building UIs"),
    "Vue.js": ("Frontend", "Progressive JavaScript framework"),
    "Angular": ("Frontend", "TypeScript web framework"),
    "Svelte": ("Frontend", "Compile-time JavaScript framework"),
    "jQuery": ("Frontend", "JavaScript library"),
    "Bootstrap": ("Frontend", "CSS framework"),
    "Tailwind CSS": ("Frontend", "Utility-first CSS framework"),
    "Backbone.js": ("Frontend", "JavaScript MVC framework"),
    "Ember.js": ("Frontend", "JavaScript framework"),
    "Node.js": ("Runtime", "JavaScript runtime environment"),
    "Deno": ("Runtime", "JavaScript/TypeScript runtime"),
    "Bun": ("Runtime", "Fast JavaScript runtime"),
    "Express.js": ("Backend", "Node.js web framework"),
    "Django": ("Backend", "Python web framework"),
    "Flask": ("Backend", "Lightweight Python web framework"),
    "Rails": ("Backend", "Ruby web framework"),
    "Laravel": ("Backend", "PHP web framework"),
    "Spring": ("Backend", "Java application framework"),
    "ASP.NET": ("Backend", "Microsoft web framework"),
    ".NET": ("Backend", "Microsoft development platform"),
    "CLR": ("Runtime", "Common Language Runtime for .NET"),
    "JVM": ("Runtime", "Java Virtual Machine"),
    "Cocoa": ("Library", "Apple's native API for macOS"),
    "Cocoa Touch": ("Library", "Apple's native API for iOS"),
    "Cocoa text system": ("Library", "macOS text handling framework"),
    "Qt": ("Library", "Cross-platform application framework"),
    "GTK": ("Library", "Cross-platform widget toolkit"),
    "wxWidgets": ("Library", "Cross-platform GUI library"),
    "FLTK": ("Library", "Fast Light Toolkit"),
    "SDL": ("Library", "Simple DirectMedia Layer"),
    "OpenGL": ("Library", "Graphics rendering API"),
    "DirectX": ("Library", "Microsoft multimedia API"),
    "Vulkan": ("Library", "Low-level graphics API"),
    "Electron": ("Library", "Cross-platform desktop apps with JavaScript"),
    "Chromium Embedded Framework": ("Library", "Embed Chromium in apps"),
    "Mustache": ("Library", "Logic-less template system"),
    "Handlebars": ("Library", "Semantic templates extension of Mustache"),
    "Zend": ("Library", "PHP framework company"),
    "nopCommerce": ("Library", "Open-source e-commerce platform"),
    "Apache OFBiz": ("Library", "Open-source ERP and e-commerce"),
    "Appcelerator": ("Mobile", "Mobile development platform"),
    "React Native": ("Mobile", "Cross-platform mobile framework"),
    "Flutter": ("Mobile", "Google's UI toolkit"),
    "Xamarin": ("Mobile", "Cross-platform mobile development"),
    "Ionic": ("Mobile", "Cross-platform mobile framework"),
    "Cordova": ("Mobile", "Mobile apps with HTML/CSS/JS"),
    "PhoneGap": ("Mobile", "Mobile development framework"),
    "Kivy": ("Mobile", "Python framework for cross-platform apps"),
    "Mobiles": ("Mobile", "Mobile application development topic"),
    
    # Databases
    "MySQL": ("Database", "Open-source relational database"),
    "PostgreSQL": ("Database", "Advanced open-source database"),
    "SQLite": ("Database", "Embedded relational database"),
    "Oracle": ("Database", "Enterprise relational database"),
    "SQL Server": ("Database", "Microsoft relational database"),
    "MongoDB": ("Database", "Document-oriented NoSQL database"),
    "Redis": ("Database", "In-memory data structure store"),
    "Elasticsearch": ("Database", "Search and analytics engine"),
    "Cassandra": ("Database", "Distributed NoSQL database"),
    "CouchDB": ("Database", "Document-oriented database"),
    "Firebase": ("Database", "Google's app development platform"),
    "DynamoDB": ("Database", "AWS NoSQL database"),
    "MariaDB": ("Database", "MySQL fork"),
    "AWS Aurora": ("Database", "Amazon's MySQL/PostgreSQL-compatible database"),
    "Microsoft Azure SQL": ("Database", "Azure's SQL database service"),
    "Berkeley DB": ("Database", "Embedded key-value database"),
    "Derby": ("Database", "Apache's Java relational database"),
    "Apache Jackrabbit": ("Database", "Content repository implementation"),
    
    # Build Tools
    "Make": ("Build Tool", "Build automation tool"),
    "CMake": ("Build Tool", "Cross-platform build system"),
    "Autotools": ("Build Tool", "GNU build system"),
    "Ninja": ("Build Tool", "Small build system"),
    "Maven": ("Build Tool", "Java build tool"),
    "Gradle": ("Build Tool", "Build automation tool"),
    "Ant": ("Build Tool", "Java build tool"),
    "SBT": ("Build Tool", "Scala build tool"),
    "Bazel": ("Build Tool", "Build and test tool by Google"),
    "Buck": ("Build Tool", "Build system by Meta"),
    "Webpack": ("Build Tool", "JavaScript module bundler"),
    "Rollup": ("Build Tool", "JavaScript module bundler"),
    "Parcel": ("Build Tool", "Zero-config build tool"),
    "Vite": ("Build Tool", "Next-gen frontend build tool"),
    "esbuild": ("Build Tool", "Fast JavaScript bundler"),
    "Turbopack": ("Build Tool", "Rust-based bundler"),
    "Gulp": ("Build Tool", "JavaScript task runner"),
    "Grunt": ("Build Tool", "JavaScript task runner"),
    
    # Package Managers
    "npm": ("Package Manager", "Node.js package manager"),
    "NPM": ("Package Manager", "Node.js package manager"),
    "Yarn": ("Package Manager", "Fast dependency manager"),
    "pnpm": ("Package Manager", "Fast, disk space efficient package manager"),
    "pip": ("Package Manager", "Python package installer"),
    "Conda": ("Package Manager", "Package and environment manager"),
    "Cargo": ("Package Manager", "Rust package manager"),
    "gem": ("Package Manager", "Ruby package manager"),
    "Composer": ("Package Manager", "PHP dependency manager"),
    "NuGet": ("Package Manager", ".NET package manager"),
    "CocoaPods": ("Package Manager", "iOS dependency manager"),
    "Homebrew": ("Package Manager", "macOS package manager"),
    "Chocolatey": ("Package Manager", "Windows package manager"),
    "apt": ("Package Manager", "Debian package manager"),
    "yum": ("Package Manager", "RPM package manager"),
    "pacman": ("Package Manager", "Arch Linux package manager"),
    
    # DevOps & CI/CD
    "Jenkins": ("DevOps", "Open-source automation server"),
    "GitHub Actions": ("DevOps", "CI/CD platform by GitHub"),
    "GitLab CI": ("DevOps", "CI/CD by GitLab"),
    "CircleCI": ("DevOps", "CI/CD platform"),
    "Travis CI": ("DevOps", "Hosted CI service"),
    "TeamCity": ("DevOps", "CI/CD by JetBrains"),
    "Bamboo": ("DevOps", "CI/CD by Atlassian"),
    "Azure DevOps": ("DevOps", "Microsoft DevOps services"),
    "Microsoft Team Foundation Server": ("DevOps", "Microsoft's ALM platform"),
    "Ansible": ("DevOps", "Automation and configuration management"),
    "Puppet": ("DevOps", "Configuration management"),
    "Chef": ("DevOps", "Infrastructure automation"),
    "Terraform": ("DevOps", "Infrastructure as code"),
    "Pulumi": ("DevOps", "Infrastructure as code"),
    "Vagrant": ("DevOps", "Development environment management"),
    "Packer": ("DevOps", "Machine image builder"),
    "SaltStack": ("DevOps", "Configuration management"),
    "ArgoCD": ("DevOps", "GitOps continuous delivery"),
    "Flux": ("DevOps", "GitOps for Kubernetes"),
    "Spinnaker": ("DevOps", "Multi-cloud continuous delivery"),
    "Octopus Deploy": ("DevOps", "Deployment automation"),
    
    # Containers & Orchestration
    "Docker": ("Container", "Container platform"),
    "Kubernetes": ("Container", "Container orchestration"),
    "Podman": ("Container", "Daemonless container engine"),
    "containerd": ("Container", "Container runtime"),
    "CRI-O": ("Container", "Kubernetes container runtime"),
    "LXC": ("Container", "Linux containers"),
    "LXD": ("Container", "System container manager"),
    "rkt": ("Container", "Container runtime"),
    "OpenShift": ("Container", "Enterprise Kubernetes platform"),
    "Rancher": ("Container", "Kubernetes management platform"),
    "Nomad": ("Container", "Workload orchestrator"),
    "Docker Compose": ("Container", "Multi-container Docker applications"),
    "Docker Swarm": ("Container", "Docker-native clustering"),
    "Helm": ("Container", "Kubernetes package manager"),
    "Istio": ("Container", "Service mesh for Kubernetes"),
    "Linkerd": ("Container", "Service mesh"),
    "Envoy": ("Container", "Edge and service proxy"),
    
    # Cloud Platforms
    "AWS": ("Cloud", "Amazon Web Services"),
    "Amazon Web Services": ("Cloud", "Cloud computing platform"),
    "Azure": ("Cloud", "Microsoft cloud platform"),
    "Google Cloud": ("Cloud", "Google Cloud Platform"),
    "GCP": ("Cloud", "Google Cloud Platform"),
    "IBM Cloud": ("Cloud", "IBM's cloud platform"),
    "Oracle Cloud": ("Cloud", "Oracle's cloud platform"),
    "Alibaba Cloud": ("Cloud", "Alibaba's cloud platform"),
    "Heroku": ("Cloud", "Platform as a Service"),
    "Fly.io": ("Cloud", "App deployment platform"),
    "Render": ("Cloud", "Cloud application platform"),
    "Railway": ("Cloud", "Infrastructure platform"),
    "PlanetScale": ("Cloud", "Serverless MySQL platform"),
    "Supabase": ("Cloud", "Open-source Firebase alternative"),
    "Neon": ("Cloud", "Serverless Postgres"),
    "Microsoft Small Basic": ("Programming Language", "Beginner-friendly programming language"),
    
    # Monitoring & Logging
    "Prometheus": ("Monitoring", "Monitoring and alerting toolkit"),
    "Grafana": ("Monitoring", "Metrics visualization and monitoring"),
    "Datadog": ("Monitoring", "Cloud monitoring and analytics"),
    "New Relic": ("Monitoring", "Application performance monitoring"),
    "Dynatrace": ("Monitoring", "Software intelligence platform"),
    "AppDynamics": ("Monitoring", "Application performance management"),
    "Nagios": ("Monitoring", "IT infrastructure monitoring"),
    "Zabbix": ("Monitoring", "Enterprise monitoring solution"),
    "Icinga": ("Monitoring", "Open-source monitoring"),
    "Sensu": ("Monitoring", "Observability pipeline"),
    "PagerDuty": ("Monitoring", "Incident management platform"),
    "OpsGenie": ("Monitoring", "Alert and incident management"),
    "VictorOps": ("Monitoring", "Incident management"),
    "Logstash": ("Monitoring", "Log processing pipeline"),
    "Fluentd": ("Monitoring", "Open-source data collector"),
    "Vector": ("Monitoring", "High-performance observability pipeline"),
    "ELK Stack": ("Monitoring", "Elasticsearch, Logstash, Kibana"),
    "Debugger": ("Debugging", "Tools for debugging code"),
    
    # Testing
    "Selenium": ("Testing", "Browser automation framework"),
    "Cypress": ("Testing", "JavaScript end-to-end testing"),
    "Playwright": ("Testing", "Cross-browser testing framework"),
    "Puppeteer": ("Testing", "Headless Chrome automation"),
    "Jest": ("Testing", "JavaScript testing framework"),
    "Mocha": ("Testing", "JavaScript test framework"),
    "Jasmine": ("Testing", "BDD testing framework"),
    "Karma": ("Testing", "JavaScript test runner"),
    "pytest": ("Testing", "Python testing framework"),
    "unittest": ("Testing", "Python testing module"),
    "JUnit": ("Testing", "Java testing framework"),
    "TestNG": ("Testing", "Java testing framework"),
    "NUnit": ("Testing", "NET testing framework"),
    "xUnit": ("Testing", ".NET testing framework"),
    "RSpec": ("Testing", "Ruby testing framework"),
    "Cucumber": ("Testing", "BDD testing tool"),
    "Robot Framework": ("Testing", "Generic test automation"),
    "Postman": ("Testing", "API testing and development"),
    "Insomnia": ("Testing", "API client and testing"),
    "SoapUI": ("Testing", "API testing tool"),
    "JMeter": ("Testing", "Load testing tool"),
    "Gatling": ("Testing", "Load testing framework"),
    "Locust": ("Testing", "Load testing in Python"),
    "k6": ("Testing", "Load testing tool"),
    "Artillery": ("Testing", "Load testing toolkit"),
    "Code coverage": ("Testing", "Measuring test coverage"),
    
    # Security
    "Vault": ("Security", "Secrets management by HashiCorp"),
    "1Password": ("Security", "Password manager"),
    "LastPass": ("Security", "Password management"),
    "Bitwarden": ("Security", "Open-source password manager"),
    "KeePass": ("Security", "Free password manager"),
    "CyberArk": ("Security", "Privileged access management"),
    "Okta": ("Security", "Identity and access management"),
    "Auth0": ("Security", "Authentication platform"),
    "Keycloak": ("Security", "Open-source identity management"),
    "OWASP": ("Security", "Web application security project"),
    "Snyk": ("Security", "Developer security platform"),
    "SonarQube": ("Security", "Code quality and security"),
    "Checkmarx": ("Security", "Application security testing"),
    "Veracode": ("Security", "Application security"),
    "Fortify": ("Security", "Application security platform"),
    "Burp Suite": ("Security", "Web security testing"),
    "Nessus": ("Security", "Vulnerability scanner"),
    "Qualys": ("Security", "Cloud security and compliance"),
    "OpenSSL": ("Security", "TLS/SSL toolkit"),
    "Let's Encrypt": ("Security", "Free SSL certificates"),
    "Certbot": ("Security", "ACME client for Let's Encrypt"),
    
    # Documentation
    "Sphinx": ("Documentation", "Python documentation generator"),
    "MkDocs": ("Documentation", "Static site generator for docs"),
    "Docusaurus": ("Documentation", "Documentation website generator"),
    "GitBook": ("Documentation", "Documentation platform"),
    "Read the Docs": ("Documentation", "Documentation hosting"),
    "Swagger": ("Documentation", "API documentation"),
    "OpenAPI": ("Documentation", "API specification"),
    "Javadoc": ("Documentation", "Java documentation generator"),
    "JSDoc": ("Documentation", "JavaScript documentation generator"),
    "Doxygen": ("Documentation", "Documentation from source code"),
    "Rustdoc": ("Documentation", "Rust documentation tool"),
    "MDN Web Docs": ("Documentation", "Web platform documentation"),
    "arXiv": ("Documentation", "Research paper repository"),
    "XUL": ("Documentation", "Mozilla UI language (deprecated)"),
    
    # CLI Tools
    "command line interface": ("CLI", "Text-based interface for programs"),
    "Terminal": ("CLI", "Command line interface application"),
    "iTerm2": ("CLI", "macOS terminal emulator"),
    "Hyper": ("CLI", "Cross-platform terminal"),
    "Windows Terminal": ("CLI", "Microsoft's modern terminal"),
    "Alacritty": ("CLI", "GPU-accelerated terminal"),
    "Kitty": ("CLI", "Fast cross-platform terminal"),
    "tmux": ("CLI", "Terminal multiplexer"),
    "Screen": ("CLI", "Terminal window manager"),
    "Zsh": ("CLI", "Z shell"),
    "Bash": ("CLI", "Bourne Again Shell"),
    "Fish": ("CLI", "Friendly interactive shell"),
    "PowerShell": ("CLI", "Microsoft's task automation shell"),
    "Oh My Zsh": ("CLI", "Zsh configuration framework"),
    "Cygwin": ("CLI", "Unix tools for Windows"),
    "MSYS2": ("CLI", "Software distribution for Windows"),
    "MinGW": ("CLI", "Minimalist GNU for Windows"),
    "BusyBox": ("CLI", "Unix utilities in a single executable"),
    "Midnight Commander": ("CLI", "Visual file manager"),
    
    # Code Quality
    "ESLint": ("Code Quality", "JavaScript linter"),
    "Prettier": ("Code Quality", "Code formatter"),
    "Stylelint": ("Code Quality", "CSS linter"),
    "Pylint": ("Code Quality", "Python linter"),
    "Black": ("Code Quality", "Python code formatter"),
    "Flake8": ("Code Quality", "Python linting tool"),
    "RuboCop": ("Code Quality", "Ruby linter"),
    "Clippy": ("Code Quality", "Rust linter"),
    "rustfmt": ("Code Quality", "Rust code formatter"),
    "gofmt": ("Code Quality", "Go code formatter"),
    "golangci-lint": ("Code Quality", "Go linter aggregator"),
    "Code refactoring": ("Code Quality", "Restructuring existing code"),
    "Code completion": ("Code Quality", "Intelligent code suggestions"),
    "Auto-complete": ("Code Quality", "Automatic code completion"),
    "Class browser": ("Code Quality", "Tool to view class hierarchies"),
    
    # Programming Languages
    "Go": ("Programming Language", "Statically typed language by Google"),
    "Rust": ("Programming Language", "Systems programming language"),
    "Python": ("Programming Language", "High-level programming language"),
    "JavaScript": ("Programming Language", "Web scripting language"),
    "TypeScript": ("Programming Language", "Typed JavaScript superset"),
    "Java": ("Programming Language", "Object-oriented programming language"),
    "C": ("Programming Language", "Low-level systems language"),
    "C++": ("Programming Language", "Object-oriented systems language"),
    "C#": ("Programming Language", "Microsoft's programming language"),
    "Ruby": ("Programming Language", "Dynamic programming language"),
    "PHP": ("Programming Language", "Server-side scripting language"),
    "Perl": ("Programming Language", "High-level scripting language"),
    "Scala": ("Programming Language", "Functional/OO JVM language"),
    "Kotlin": ("Programming Language", "Modern JVM language"),
    "Swift": ("Programming Language", "Apple's programming language"),
    "Objective-C": ("Programming Language", "Apple's legacy language"),
    "R": ("Programming Language", "Statistical computing language"),
    "Julia": ("Programming Language", "High-performance scientific computing"),
    "Haskell": ("Programming Language", "Purely functional language"),
    "Erlang": ("Programming Language", "Concurrent programming language"),
    "Elixir": ("Programming Language", "Functional language on Erlang VM"),
    "Clojure": ("Programming Language", "Lisp dialect for JVM"),
    "F#": ("Programming Language", ".NET functional language"),
    "OCaml": ("Programming Language", "Functional programming language"),
    "Lua": ("Programming Language", "Lightweight scripting language"),
    "Dart": ("Programming Language", "Google's client-optimized language"),
    "Groovy": ("Programming Language", "Dynamic JVM language"),
    "Basic": ("Programming Language", "Beginner's programming language"),
    "BASIC": ("Programming Language", "Beginner's programming language"),
    "Visual Basic": ("Programming Language", "Microsoft's RAD language"),
    "VB.NET": ("Programming Language", ".NET version of Visual Basic"),
    "Pascal": ("Programming Language", "Structured programming language"),
    "Object Pascal": ("Programming Language", "Object-oriented Pascal"),
    "COBOL": ("Programming Language", "Business-oriented language"),
    "Fortran": ("Programming Language", "Scientific computing language"),
    "Ada": ("Programming Language", "High-integrity systems language"),
    "Assembly": ("Programming Language", "Low-level programming language"),
    "MASM": ("Programming Language", "Microsoft Macro Assembler"),
    "NASM": ("Programming Language", "Netwide Assembler"),
    "FASM": ("Programming Language", "Flat Assembler"),
    "Lisp": ("Programming Language", "List processing language"),
    "Common Lisp": ("Programming Language", "Lisp dialect"),
    "Scheme": ("Programming Language", "Minimalist Lisp dialect"),
    "Racket": ("Programming Language", "Lisp-derived language"),
    "Prolog": ("Programming Language", "Logic programming language"),
    "Smalltalk": ("Programming Language", "Object-oriented language"),
    "Squeak": ("Programming Language", "Open Smalltalk implementation"),
    "Pharo": ("Programming Language", "Modern Smalltalk"),
    "Tcl": ("Programming Language", "Tool Command Language"),
    "Awk": ("Programming Language", "Text processing language"),
    "Sed": ("Programming Language", "Stream editor"),
    "SQL": ("Programming Language", "Database query language"),
    "PL/SQL": ("Programming Language", "Oracle's procedural SQL"),
    "T-SQL": ("Programming Language", "Microsoft's SQL extension"),
    "XSLT": ("Programming Language", "XML transformation language"),
    "XQuery": ("Programming Language", "XML query language"),
    "Bash": ("Programming Language", "Unix shell scripting"),
    "PowerShell": ("Programming Language", "Microsoft's shell language"),
    "Batch": ("Programming Language", "Windows command scripting"),
    "TeX": ("Programming Language", "Document typesetting system"),
    "LaTeX": ("Programming Language", "Document preparation system"),
    "Markdown": ("Programming Language", "Lightweight markup language"),
    "YAML": ("Programming Language", "Data serialization language"),
    "JSON": ("Programming Language", "Data interchange format"),
    "XML": ("Programming Language", "Extensible markup language"),
    "HTML": ("Programming Language", "Web markup language"),
    "CSS": ("Programming Language", "Web styling language"),
    "SASS": ("Programming Language", "CSS preprocessor"),
    "LESS": ("Programming Language", "CSS preprocessor"),
    "WebAssembly": ("Programming Language", "Binary instruction format for web"),
    "Wasm": ("Programming Language", "Binary instruction format for web"),
    "Zig": ("Programming Language", "Systems programming language"),
    "Nim": ("Programming Language", "Statically typed compiled language"),
    "Crystal": ("Programming Language", "Ruby-like compiled language"),
    "V": ("Programming Language", "Simple compiled language"),
    "Odin": ("Programming Language", "Systems programming language"),
    "Chapel": ("Programming Language", "Parallel programming language"),
    "D": ("Programming Language", "Systems programming language"),
    "Vala": ("Programming Language", "GNOME programming language"),
    "Haxe": ("Programming Language", "Cross-platform language"),
    "ActionScript": ("Programming Language", "Flash scripting language"),
    "CoffeeScript": ("Programming Language", "JavaScript transpiler language"),
    "LiveScript": ("Programming Language", "JavaScript transpiler"),
    "Elm": ("Programming Language", "Functional web language"),
    "PureScript": ("Programming Language", "Strongly-typed to JS language"),
    "ReasonML": ("Programming Language", "OCaml syntax for JavaScript"),
    "ClojureScript": ("Programming Language", "Clojure to JavaScript"),
    "Allegro Common Lisp": ("Programming Language", "Commercial Common Lisp"),
    "Cincom": ("Programming Language", "Smalltalk vendor"),
    "Basic-256": ("Programming Language", "Educational BASIC dialect"),
    "Basic4GL": ("Programming Language", "BASIC for OpenGL"),
    "NS Basic": ("Programming Language", "BASIC development environment"),
    "CA-Realizer": ("Programming Language", "Visual BASIC-like language"),
    "C compiler": ("Programming Language", "Compiler for C language"),
    
    # PDF / Document tools
    "Adobe Acrobat": ("Collaboration", "PDF creation and editing software"),
    "Foxit Reader": ("Collaboration", "PDF reader"),
    "PDF.js": ("Library", "PDF rendering in JavaScript"),
    
    # Licenses
    "MIT": ("Documentation", "MIT software license"),
    "GPL": ("Documentation", "GNU General Public License"),
    "Apache License": ("Documentation", "Apache Software License"),
    "BSD 3-clause": ("Documentation", "BSD license variant"),
    "Mozilla Public License": ("Documentation", "MPL license"),
    "LGPL": ("Documentation", "Lesser GPL"),
    "CPAL": ("Documentation", "Common Public Attribution License"),
    "ClArtistic": ("Documentation", "Clarified Artistic License"),
    "commercial": ("Documentation", "Commercial license"),
    
    # APIs
    "REST": ("API", "Representational State Transfer"),
    "GraphQL": ("API", "Query language for APIs"),
    "gRPC": ("API", "High-performance RPC framework"),
    "SOAP": ("API", "Simple Object Access Protocol"),
    "WebSocket": ("API", "Full-duplex communication protocol"),
    "OAuth": ("API", "Authorization framework"),
    "OpenID": ("API", "Authentication layer"),
    "JWT": ("API", "JSON Web Tokens"),
    "Apache Sling": ("API", "Web application framework"),
    "Apache Roller": ("API", "Blog server software"),
    "App Inventor for Android's visual block language (MIT App Inventor)": ("Mobile", "Visual programming for Android"),
    
    # Misc
    "ACiDDraw": ("Design", "ANSI art editor"),
    "ASCII": ("Documentation", "Character encoding standard"),
    "AOLserver": ("Backend", "Web server"),
    "Apps Marketplace Profile": ("API", "API profile for app stores"),
    "Borland": ("IDE/Editor", "Software development company"),
    "Borland Kylix": ("IDE/Editor", "Delphi for Linux"),
    "Budget management": ("Collaboration", "Financial planning tools"),
    "comparison": ("Documentation", "Comparative analysis"),
    "citation needed": ("Documentation", "Wikipedia citation marker"),
    "clarification needed": ("Documentation", "Wikipedia clarity marker"),
    "dead link": ("Documentation", "Broken hyperlink marker"),
    "Developer": ("Documentation", "Software developer role"),
    "Foswiki": ("CMS", "Enterprise wiki software"),
    "Google Apps": ("Collaboration", "Google's productivity apps"),
    "NetSuite": ("Business", "Cloud ERP and business software"),
    "O26": ("Hardware", "Vintage software"),
    "O3Spaces": ("Collaboration", "Document management"),
    "Microweber": ("CMS", "Drag-and-drop CMS"),
}

# Update the data
changes_made = []
for item in data:
    name = item.get('name', '')
    original_category = item.get('category', '')
    original_desc = item.get('description', '')
    
    changed = False
    
    # Check if it's in our known tools list
    if name in KNOWN_TOOLS:
        new_cat, new_desc = KNOWN_TOOLS[name]
        if original_category != new_cat or (original_desc in BAD_DESCRIPTIONS or original_desc != new_desc):
            item['category'] = new_cat
            item['description'] = new_desc
            changes_made.append({
                'name': name,
                'old_category': original_category,
                'new_category': new_cat,
                'old_desc': original_desc if original_desc in BAD_DESCRIPTIONS else "(kept)",
                'new_desc': new_desc if original_desc in BAD_DESCRIPTIONS else "(kept)"
            })
            changed = True
    
    # For items still categorized as "Tool" with bad descriptions
    elif original_category == 'Tool' and original_desc in BAD_DESCRIPTIONS:
        # Try to infer category from name/URL
        name_lower = name.lower()
        url = item.get('url', '').lower()
        
        new_cat = None
        
        # IDE/Editor patterns
        if any(x in name_lower for x in ['editor', 'ide', 'studio', 'vim', 'emacs', 'notepad', 'edit']):
            new_cat = 'IDE/Editor'
        elif any(x in name_lower for x in ['cms', 'wiki', 'blog', 'drupal', 'wordpress', 'joomla']):
            new_cat = 'CMS'
        elif any(x in name_lower for x in ['project', 'task', 'team', 'collab', 'office', 'document']):
            new_cat = 'Collaboration'
        elif any(x in name_lower for x in ['database', 'sql', 'db']):
            new_cat = 'Database'
        elif any(x in name_lower for x in ['cloud', 'azure', 'aws', 'amazon']):
            new_cat = 'Cloud'
        elif any(x in name_lower for x in ['hosting', 'domain', 'registrar', 'dns']):
            new_cat = 'Hosting'
        elif any(x in name_lower for x in ['test', 'selenium', 'debug']):
            new_cat = 'Testing'
        elif any(x in name_lower for x in ['monitor', 'log', 'metric']):
            new_cat = 'Monitoring'
        elif any(x in name_lower for x in ['container', 'docker', 'kubernetes']):
            new_cat = 'Container'
        elif any(x in name_lower for x in ['security', 'auth', 'encrypt', 'ssl']):
            new_cat = 'Security'
        elif any(x in name_lower for x in ['mobile', 'android', 'ios', 'phone']):
            new_cat = 'Mobile'
        elif any(x in name_lower for x in ['os', 'operating', 'linux', 'windows', 'unix', 'dos']):
            new_cat = 'Operating System'
        elif any(x in name_lower for x in ['license', 'gpl', 'mit', 'apache', 'bsd']):
            new_cat = 'Documentation'
        elif any(x in name_lower for x in ['api', 'rest', 'graphql']):
            new_cat = 'API'
        elif any(x in name_lower for x in ['git', 'svn', 'version', 'mercurial', 'cvs']):
            new_cat = 'Version Control'
        
        if new_cat:
            item['category'] = new_cat
            item['description'] = f"[Needs review] {original_desc}"
            changes_made.append({
                'name': name,
                'old_category': original_category,
                'new_category': new_cat,
                'old_desc': original_desc,
                'new_desc': item['description']
            })

# Save the updated data
with open('data.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

# Print summary
print(f"Total changes made: {len(changes_made)}")
print("\n" + "=" * 100)
print("CHANGES MADE:")
print("=" * 100)

for change in changes_made[:100]:  # Show first 100
    print(f"\n{change['name']}:")
    print(f"  Category: {change['old_category']} -> {change['new_category']}")
    if change['old_desc'] != "(kept)":
        print(f"  Description: \"{change['old_desc'][:50]}...\" -> \"{change['new_desc'][:50]}...\"")

if len(changes_made) > 100:
    print(f"\n... and {len(changes_made) - 100} more changes")

# Save change report
with open('reclassification_report.json', 'w', encoding='utf-8') as f:
    json.dump(changes_made, f, indent=2, ensure_ascii=False)

print(f"\n\nFull report saved to reclassification_report.json")
print(f"Data file updated: data.json")
